### ISSUE TITLE
Send BTC to LTC

### ISSUE THREAD

**Issue by gunjanbacancy** [hellovoid/gdax#10]
Hi,
I have BTC address and LTC address created with coinbase API, so is it possible for transfer BTC to LTC using API ?
Thanks in advance.

**Comment by gunjanbacancy** [comment]
Any Answer ?

**Comment by hellovoid** [comment]
Hello,

It is not possible to transfer BTC to LTC directly, 
but you can deposit BTC from coinbase to gdax, sell BTC-USD, buy LTC-USD and withdraw LTC to coinbase. :)
