### ISSUE TITLE
Unsupported operand types 

### ISSUE THREAD

**Issue by kfo2010** [hellovoid/gdax#3]
`Fatal error: Uncaught Error: Unsupported operand types in /vendor/hellovoid/gdax/src/Client.php:67 Stack trace: #0 /vendor/hellovoid/gdax/src/Client.php(88): Hellovoid\Gdax\Client->getAndDecodeData('accounts') #1 gdax.php(33): Hellovoid\Gdax\Client->getAccounts() #2 /modules/tests/gdax.php(75): gdax_get_balances(2) #3 /web/rr/index.php(123): require_once('...') #4 {main} thrown in /vendor/hellovoid/gdax/src/Client.php on line 67`

**Comment by hellovoid** [comment]
Fixed https://github.com/hellovoid/gdax/commit/b892e2cdda5d8903cabcd40e6fc71a43ad059e68#diff-ff73e042e738204c6da009e2ed19f783.
