### ISSUE TITLE
Unsupported Operand Types - GitHub User Error???

### ISSUE THREAD

**Issue by pha3z** [hellovoid/gdax#5]
I installed the library using "composer require hellovoid/gdax" as directed.  Everything seemed to work fine.

When I attempted to call $client->position(); I got the Unsupported Operands error mentioned on this issue:
 [https://github.com/hellovoid/gdax/issues/3](url)

So I checked the changed code on the commit regarding the issue and saw the line 66 change from "null" to "[]".  I made the change in my own copy of hellovoid/gdax/src/Client.php and it fixed the problem.

My question is:  Why did my brand new installed copy of Client.php still have the old code with the line 66 saying "null" instead of the change that was made 16 days ago.

Am I using GitHub incorrectly?  I somehow ended up with an older committed version?

**Comment by hellovoid** [comment]
Hello, just created new release. Please try 1.0.1

**Comment by pha3z** [comment]
I am not experienced with GitHub, so maybe I'm missing something, but the main page still says the src was last updated 26 days ago.
I'm talking about this page here:  https://github.com/hellovoid/gdax

On the right side of the src directory it says a pagination issue was fixed 26 days ago.  If the code has been updated, shouldn't that 26 days change to 1 day ago or so many hours ago?

**Comment by hellovoid** [comment]
Thanks for reply,
You can check it out https://github.com/hellovoid/gdax/releases
