### ISSUE TITLE
ServerTime: Recommended Feature

### ISSUE THREAD

**Issue by pha3z** [hellovoid/gdax#6]
I recommend adding this code to the very end of Client.php file:

`    public function getServerTime()
    {
		return $this->getAndDecodeData('time');    
   	}`

It returns the current Server Time in both ISO and Unix EPOCH formats.  Example use would be if you want to fetch historic data that goes right up to the most recent moment in time.  You need the server time to do that.

**Comment by pha3z** [comment]
Side note:  I noticed that if you request data with an End time within about 5 seconds of the current server time, gdax's behavior changes.  It returns 400 bars of historical data automatically, regardless of your specified Start time.

**Comment by hellovoid** [comment]
Thanks 👍

https://github.com/hellovoid/gdax/commit/c70b9ab0beb457c0088d1f4456673c485151da8e#diff-ff73e042e738204c6da009e2ed19f783
