### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by Josh-123** [hellovoid/gdax#8]
I tried the following code and I am getting blank output. Can you please provide a working code to getAccounts?

require_once __DIR__ . '/composer/autoload_real.php';
return ComposerAutoloaderInitc4aca15140bd590e171ded1912c8b2a0::getLoader();	
	
use Hellovoid\Gdax\Configuration;
use Hellovoid\Gdax\Client;
 
$apiKey = 'myapikey';
$apiSecret = 'mysecretky';
$apiPassphrase = 'mypassphrase';

$configuration = Configuration::apiKey($apiKey, $apiSecret, $apiPassphrase);
$client = Client::create($configuration);
print_r($client->getAccounts());

**Comment by nextpulse** [comment]
I have it working. The only difference is how I include the autoload.php:

require_once('vendor/autoload.php');

use Hellovoid\Gdax\Configuration;
use Hellovoid\Gdax\Client;
