### ISSUE TITLE
Pagination not fully implemented?

### ISSUE THREAD

**Issue by nextpulse** [hellovoid/gdax#9]
According to the gdax doc: 

https://docs.gdax.com/#pagination

"before and after cursors are available via response headers CB-BEFORE and CB-AFTER. "

There are no methods to get these values and set the pagination object.

**Comment by hellovoid** [comment]
Hello,

https://github.com/hellovoid/gdax#pagination-ref

**Comment by nextpulse** [comment]
The $before and $after needs to be set via CB-BEFORE and CB-AFTER

Otherwise, where will the values come from?

**Comment by hellovoid** [comment]
https://github.com/hellovoid/gdax/blob/aa77af1b6a1e6159686b7de9b74544430ba96672/src/Client.php#L64

**Comment by nextpulse** [comment]
That is a private function.

Do you have a working example of pagination code? 

The example in the readme assumes $before, $after are set.

**Comment by hellovoid** [comment]
`
use Hellovoid\Gdax\Configuration;
use Hellovoid\Gdax\Client;
use Hellovoid\Gdax\Pagination;

$configuration = Configuration::apiKey($apiKey, $apiSecret, $apiPassphrase);

$pagination = Pagination::create();

$client = Client::create($configuration, $pagination);

$fills = $client->getFills([
    'order_id'   => 'all',
    'product_id' => 'all'
]);

if (count($fills) > 0) {

    $latestFill = $fills[0]['details']['trade_id'];

    $pagination->setStartingAfter($latestFill);

    $fills = $client->getFills([
        'order_id'   => 'all',
        'product_id' => 'all'
    ]);
    
}
`

**Comment by nextpulse** [comment]
Using 'trade_id' is probably not the best approach (chronological order is not guaranteed). Any reason why the code is not using the response headers (CB-BEFORE and CB-AFTER) to extract these values?

**Comment by nextpulse** [comment]
If you are modelling after the coinbase php - they have a hasNextPage() method. Also the Param::FETCH_ALL => true options.

Which is probably taking advantage of the underlying param 'next_uri'.  I think you can do something simiar - but use the response headers instead.

**Comment by hellovoid** [comment]
https://docs.gdax.com/#list-fills

..."PAGINATION

Fills are returned sorted by descending trade_id from the largest trade_id to the smallest trade_id. The CB-BEFORE header will have this first trade id so that future requests using the cb-before parameter will fetch fills with a greater trade id (newer fills)."

**Comment by nextpulse** [comment]
Why did you close this? The current pagination implementation is incorrect - it is applying the 'fills' pagination to the other api calls. The official gdax api doc defines it differently.

**Comment by bar1024** [comment]
You can reference the pagination cursors with `$client->getHttpClient()->getLastResponse()->getHeader('cb-after')` and `$client->getHttpClient()->getLastResponse()->getHeader('cb-before')`

**Comment by nextpulse** [comment]
Great! That's the right solution.
Maybe the readme should be updated to reflect this?
